### ISSUE TITLE
Current credential behaviour considered harmful

### ISSUE THREAD

**Issue by CharString** [svaningelgem/ruff2bitbucket#2]
While seemingly user friendly, the current behaviour described in [Security](https://github.com/svaningelgem/ruff2bitbucket?tab=readme-ov-file#security) of sending anything in the environment that looks like a pair of credentials to BitBucket is insecure. Those credentials may be of some other service, and should never be sent to Atlassian.

I suggest following whatever their app token scheme is https://developer.atlassian.com/developer-guide/start-building-with-atlassian/ , move to using [keyring](https://pypi.org/project/keyring/) to handle credentials using the OS defaults or use at least a strictly pair of environment variables that can never be mistaken for something other than to be used for this tool/BitBucket.

**Comment by svaningelgem** [comment]
Thanks for the report!

I agree with you that this is a relatively insecure design.
It just started this way because we did share a lot of passwords (yep yep... security by design 😁).


If you want I can add a token-authentication, and an optional fetching from keyring.
So you'd end up with:
- _(API token)_ `--user ... --token ...`
- _(keyring)_ `--user ... --service_name ...`
- _(envvars)_ `--uservar ... --passvar ...`
- _(user/pass)_ `--user ... --pass ...`
- _(fallback)_ current implementation: via the environment variables

WDYT?

**Comment by CharString** [comment]
It's your project, don't change it for a tyre kicker like me. 😉 I just bumped into it, thought it looked cool and I'm trying to be a good citizen and point out that the current implementation can have unhappy surprises. 🙂 

As for what I think:

Changing the default behaviour to look only for `BITBUCKET_USER` and `BITBUCKET_PASS` would be the simplest change. I do think passing in via environment is better than with command line options, for the multi-user system case.
I haven't looked into what hoops you have to jump through for an API key, but it's worth looking into if you plan to offer this as a service.
I do have experience with keyring, and it's a pretty nice library that uses whatever the OS uses for password management.

**Comment by svaningelgem** [comment]
I appreciate it!

The issue at my project was that these envvars were sometimes called USR/PASS, or BB_USER/BB_PASS, or ...
And to ease people into using the plugin, I designed it this way to find a "match" (it'll try all matches and store the last successful one).

I think I'll adjust it as proposed in the earlier comment. It's not really a lot of effort, but it'll make this project that more versatile -security wise.

**Comment by svaningelgem** [comment]
Hey @CharString , I implemented something that incorporates a lot of more possibilities to provide the user/pass.
I know you're just browsing through, but if you could check the (new) README.md, I'd be grateful.
